server:
  port: 8100
spring:
  thymeleaf:
    cache: false
  redis:
    host: 124.221.202.161
    port: 6379
    password: redisPwd

    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.221.202.161:3306/my_blog?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: mysqlPwd
    druid:
      min-idle: 5
      initial-size: 20
      max-active: 30
      max-wait: 30000
      time-between-eviction-runs-millis: 30000
      min-evictable-idle-time-millis: 200000
  elasticsearch:
    port: 9200
    host: 124.221.202.161
    password: elasticPwd
    username: elastic
  mail:
    host: smtp.qq.com
    port: 587
    username: "3409444780@qq.com"
    password: "eprcypsethjrdcba"
    protocol: smtp
    default-encoding: UTF-8

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

custom:
  my-blog:
    captcha:
      text-producer-font-color: black
      text-producer-char-length: 4
      text-producer-char-space: 4
      text-producer-font-size: 30
      image-width: 150
      image-height: 40
      session-key: verifyCode
      border: 'no'
    blog:
      max-content-length: 100000
      max-title-length: 150
      max-url-length: 150
      max-tags-length: 150
  cos:
    bucket-name: image-1312474773
    region: ap-chengdu
    app-id: 1312474773
    secret-id: AKIDWuHlGep4INI2dCoERXZP8mEEe098wa1J
    secret-key: IPRJxYzRm0FLFyZyCF5nPr7A0pYM7kJs